spring:
  redis:
    host: localhost
    port: 6379
    password: RURAL03
    sentinel:
      master: redis-master
      nodes:
        - localhost
    lettuce:
      shutdown-timeout: 200ms
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    async:
      request-timeout: -1
